version: "3"
services:
  dbpostgres:
    ports:
      - "1433:5432"
    container_name: eelc_db
    image: "postgres:12.5"
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "itsallgood"
      POSTGRES_DB: "eelc"
