version: "3"
services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azuresqledge_eelc
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: ${DB_PASS}
    ports:
      - 1433:1433
    volumes:
      - ./db/data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - default
